version: 0.0
os: linux
files:
  - source: /ci/eks-rollout-sample-1.sh
    destination: /tmp/eks-sample
hooks:
  ApplicationStop:
    - location: ci/eks-rollout-sample-1.sh
      timeout: 60
      runas: root