version: 0.0
os: linux
files:
  - source: /ci/eks-rollout-sample-1.sh
    destination: /tmp/eks-sample

permissions:
  - object: /tmp/eks-sample
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  ApplicationStop:
    - location: ci/eks-rollout-sample-1.sh
      timeout: 60
      runas: root
